name: Manual Kraken Orders

on:
  workflow_dispatch:  # Allows manual triggering
    inputs:
      coin:
        description: 'Coin to trade'
        required: true
        default: BTC
        type: choice
        options:
          - BTC
          - XRP
          - SUI
      base_price:
        description: 'First order price'
        required: false
        type: number
      price_distance:
        description: 'Distance in % between the order prices'
        required: false
        default: 1.0
        type: number
      spot:
        description: 'Use spot, not margin'
        required: false
        default: false
        type: boolean

jobs:
  place-orders:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run order script
      run: node scripts/daily_orders.js ${{ github.event.inputs.coin }} ${{ github.event.inputs.base_price }} ${{ github.event.inputs.price_distance }} ${{ github.event.inputs.spot }}
      env:
        KRAKEN_API_KEY: ${{ secrets.KRAKEN_API_KEY }}
        KRAKEN_API_SECRET: ${{ secrets.KRAKEN_API_SECRET }}
